version: "2"

services:
  db:
    image: mariadb:12.2@sha256:e16f61b8f6ed25111adbb1c5c19bbc2904efc8ed14029999af0cbe1c7ae18bf1
    restart: always
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker-persistence/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=pizza_suggester
      - MYSQL_PASSWORD=pizza_suggester
      - MYSQL_DATABASE=pizza_suggester_db

  db2:
    image: postgres@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pizza_suggester_db
      - POSTGRES_USER=pizza_suggester
      - POSTGRES_PASSWORD=pizza_suggester

  adminer:
    image: adminer@sha256:3a1582df310cf49a3c9cad2882496eed4596563f8d33250703f8b26e538cef7d
    depends_on:
      - db
      - db2
    ports:
      - 8000:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db