version: "2"

services:
  db:
    image: mariadb:12.3@sha256:a02fe89cb597d4375812b2eac90cf9d0775d4686daa7f7cc750ebbcad7525bbc
    restart: always
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker-persistence/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=pizza_suggester
      - MYSQL_PASSWORD=pizza_suggester
      - MYSQL_DATABASE=pizza_suggester_db

  db2:
    image: postgres@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pizza_suggester_db
      - POSTGRES_USER=pizza_suggester
      - POSTGRES_PASSWORD=pizza_suggester

  adminer:
    image: adminer@sha256:f742dcf1b6ca95733b54c4e020488ce78f3e774d73543a6ded9b4eaea8974f3d
    depends_on:
      - db
      - db2
    ports:
      - 8000:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db