version: "2"

services:
  db:
    image: mariadb:12.2@sha256:e0236fc6386e7eacd9359e59d0a078bd7aa0d18280d36d13061121bedeaee903
    restart: always
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker-persistence/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=pizza_suggester
      - MYSQL_PASSWORD=pizza_suggester
      - MYSQL_DATABASE=pizza_suggester_db

  db2:
    image: postgres@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pizza_suggester_db
      - POSTGRES_USER=pizza_suggester
      - POSTGRES_PASSWORD=pizza_suggester

  adminer:
    image: adminer@sha256:cc64d253db4f016cbcff2ff2f01e60ed07e74f38b4398f84d3c4fae4b5ce0e07
    depends_on:
      - db
      - db2
    ports:
      - 8000:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db