name: Create and publish a Docker image

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '.github/workflows/build-and-publish.yml'
      - '**.java'
      - '**.properties'
      - '*.gradle'
      - 'Dockerfile'


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKERHUB_IMAGENAME }}
          github-token: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: | 
            ${{ steps.meta.outputs.tags }}
            ${{ vars.DOCKERHUB_IMAGENAME }}:latest
            ${{ vars.DOCKERHUB_IMAGENAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
